import { createFileRoute } from "@tanstack/react-router";
import { buildHead } from "@/lib/seo";
import ServicePageLayout from "@/components/layout/ServicePageLayout";
import { SERVICE_CONTENT } from "@/data/serviceContent";

const data = SERVICE_CONTENT["virtual-photoshoot"];

export const Route = createFileRoute("/services/virtual-photoshoot")({
  head: () =>
    buildHead({
      title: "Virtual Photoshoot",
      description:
        "Campaign-ready product photography generated by AI. No studio, no model, no photographer. Delivered in days.",
      path: "/services/virtual-photoshoot",
    }),
  component: () => <ServicePageLayout data={data} />,
});
