// Replaces src/integrations/supabase/auth-attacher.ts. That file was
// auto-generated by Lovable's Supabase integration tooling on every save -
// this one isn't auto-generated by anything since that tooling doesn't
// apply to PocketBase, so it's now a normal, manually maintained file.
//
// Must be registered as a `functionMiddleware` in src/start.ts, otherwise
// the browser never attaches the auth token to server-fn calls that need
// requireAdminAuth (see src/integrations/pocketbase/auth-middleware.ts).
import { createMiddleware } from "@tanstack/react-start";
import { pb } from "./client";

export const attachPocketbaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const token = pb.authStore.token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
