/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkToUsRouteImport } from './routes/talk-to-us'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesIndexRouteImport } from './routes/utilities.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UtilitiesQrCodeGeneratorRouteImport } from './routes/utilities.qr-code-generator'
import { Route as UtilitiesImageConverterRouteImport } from './routes/utilities.image-converter'
import { Route as UtilitiesImageCompressorRouteImport } from './routes/utilities.image-compressor'
import { Route as UtilitiesFileConverterRouteImport } from './routes/utilities.file-converter'
import { Route as UtilitiesFileCompressorRouteImport } from './routes/utilities.file-compressor'
import { Route as UtilitiesEmailSignatureGeneratorRouteImport } from './routes/utilities.email-signature-generator'
import { Route as UtilitiesCsvCleanerRouteImport } from './routes/utilities.csv-cleaner'
import { Route as UtilitiesBackgroundRemoverRouteImport } from './routes/utilities.background-remover'
import { Route as ServicesSpeedToLeadRouteImport } from './routes/services.speed-to-lead'
import { Route as ServicesLeadReactivationRouteImport } from './routes/services.lead-reactivation'
import { Route as ServicesCustomAiSystemsRouteImport } from './routes/services.custom-ai-systems'
import { Route as ServicesCustomAgenticAiRouteImport } from './routes/services.custom-agentic-ai'
import { Route as ServicesAiVoiceAgentRouteImport } from './routes/services.ai-voice-agent'
import { Route as ProductsFlowRouteImport } from './routes/products.flow'
import { Route as ProductsChatRouteImport } from './routes/products.chat'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as PartnerReferralRouteImport } from './routes/partner.referral'
import { Route as PartnerIntegrationRouteImport } from './routes/partner.integration'
import { Route as PartnerAgencyRouteImport } from './routes/partner.agency'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'
import { Route as LegalRefundPolicyRouteImport } from './routes/legal.refund-policy'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiSubmitFormRouteImport } from './routes/api/submit-form'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin.upload'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminDashboardIndexRouteImport } from './routes/_admin.admin.dashboard.index'
import { Route as AdminAdminDashboardSubmissionsRouteImport } from './routes/_admin.admin.dashboard.submissions'
import { Route as AdminAdminDashboardSettingsRouteImport } from './routes/_admin.admin.dashboard.settings'
import { Route as AdminAdminDashboardServicesRouteImport } from './routes/_admin.admin.dashboard.services'
import { Route as AdminAdminDashboardPortfolioRouteImport } from './routes/_admin.admin.dashboard.portfolio'
import { Route as AdminAdminDashboardPartnersRouteImport } from './routes/_admin.admin.dashboard.partners'
import { Route as AdminAdminDashboardClientsRouteImport } from './routes/_admin.admin.dashboard.clients'
import { Route as AdminAdminDashboardBlogRouteImport } from './routes/_admin.admin.dashboard.blog'
import { Route as AdminAdminDashboardAuditRouteImport } from './routes/_admin.admin.dashboard.audit'
import { Route as AdminAdminDashboardPortfolioIdRouteImport } from './routes/_admin.admin.dashboard.portfolio.$id'
import { Route as AdminAdminDashboardClientsIdRouteImport } from './routes/_admin.admin.dashboard.clients.$id'
import { Route as AdminAdminDashboardBlogIdRouteImport } from './routes/_admin.admin.dashboard.blog.$id'

const TalkToUsRoute = TalkToUsRouteImport.update({
  id: '/talk-to-us',
  path: '/talk-to-us',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesIndexRoute = UtilitiesIndexRouteImport.update({
  id: '/utilities/',
  path: '/utilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesQrCodeGeneratorRoute =
  UtilitiesQrCodeGeneratorRouteImport.update({
    id: '/utilities/qr-code-generator',
    path: '/utilities/qr-code-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilitiesImageConverterRoute = UtilitiesImageConverterRouteImport.update({
  id: '/utilities/image-converter',
  path: '/utilities/image-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesImageCompressorRoute =
  UtilitiesImageCompressorRouteImport.update({
    id: '/utilities/image-compressor',
    path: '/utilities/image-compressor',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilitiesFileConverterRoute = UtilitiesFileConverterRouteImport.update({
  id: '/utilities/file-converter',
  path: '/utilities/file-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesFileCompressorRoute = UtilitiesFileCompressorRouteImport.update({
  id: '/utilities/file-compressor',
  path: '/utilities/file-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesEmailSignatureGeneratorRoute =
  UtilitiesEmailSignatureGeneratorRouteImport.update({
    id: '/utilities/email-signature-generator',
    path: '/utilities/email-signature-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilitiesCsvCleanerRoute = UtilitiesCsvCleanerRouteImport.update({
  id: '/utilities/csv-cleaner',
  path: '/utilities/csv-cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesBackgroundRemoverRoute =
  UtilitiesBackgroundRemoverRouteImport.update({
    id: '/utilities/background-remover',
    path: '/utilities/background-remover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSpeedToLeadRoute = ServicesSpeedToLeadRouteImport.update({
  id: '/services/speed-to-lead',
  path: '/services/speed-to-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeadReactivationRoute =
  ServicesLeadReactivationRouteImport.update({
    id: '/services/lead-reactivation',
    path: '/services/lead-reactivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomAiSystemsRoute = ServicesCustomAiSystemsRouteImport.update({
  id: '/services/custom-ai-systems',
  path: '/services/custom-ai-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomAgenticAiRoute = ServicesCustomAgenticAiRouteImport.update({
  id: '/services/custom-agentic-ai',
  path: '/services/custom-agentic-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiVoiceAgentRoute = ServicesAiVoiceAgentRouteImport.update({
  id: '/services/ai-voice-agent',
  path: '/services/ai-voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFlowRoute = ProductsFlowRouteImport.update({
  id: '/products/flow',
  path: '/products/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChatRoute = ProductsChatRouteImport.update({
  id: '/products/chat',
  path: '/products/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const PartnerReferralRoute = PartnerReferralRouteImport.update({
  id: '/partner/referral',
  path: '/partner/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIntegrationRoute = PartnerIntegrationRouteImport.update({
  id: '/partner/integration',
  path: '/partner/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAgencyRoute = PartnerAgencyRouteImport.update({
  id: '/partner/agency',
  path: '/partner/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundPolicyRoute = LegalRefundPolicyRouteImport.update({
  id: '/legal/refund-policy',
  path: '/legal/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitFormRoute = ApiSubmitFormRouteImport.update({
  id: '/api/submit-form',
  path: '/api/submit-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/admin/mfa',
  path: '/admin/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardIndexRoute =
  AdminAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardSubmissionsRoute =
  AdminAdminDashboardSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardSettingsRoute =
  AdminAdminDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardServicesRoute =
  AdminAdminDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardPortfolioRoute =
  AdminAdminDashboardPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardPartnersRoute =
  AdminAdminDashboardPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardClientsRoute =
  AdminAdminDashboardClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardBlogRoute = AdminAdminDashboardBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminAdminDashboardRoute,
} as any)
const AdminAdminDashboardAuditRoute =
  AdminAdminDashboardAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AdminAdminDashboardRoute,
  } as any)
const AdminAdminDashboardPortfolioIdRoute =
  AdminAdminDashboardPortfolioIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardPortfolioRoute,
  } as any)
const AdminAdminDashboardClientsIdRoute =
  AdminAdminDashboardClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardClientsRoute,
  } as any)
const AdminAdminDashboardBlogIdRoute =
  AdminAdminDashboardBlogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminDashboardBlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/integration': typeof PartnerIntegrationRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/chat': typeof ProductsChatRoute
  '/products/flow': typeof ProductsFlowRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/custom-agentic-ai': typeof ServicesCustomAgenticAiRoute
  '/services/custom-ai-systems': typeof ServicesCustomAiSystemsRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/utilities/background-remover': typeof UtilitiesBackgroundRemoverRoute
  '/utilities/csv-cleaner': typeof UtilitiesCsvCleanerRoute
  '/utilities/email-signature-generator': typeof UtilitiesEmailSignatureGeneratorRoute
  '/utilities/file-compressor': typeof UtilitiesFileCompressorRoute
  '/utilities/file-converter': typeof UtilitiesFileConverterRoute
  '/utilities/image-compressor': typeof UtilitiesImageCompressorRoute
  '/utilities/image-converter': typeof UtilitiesImageConverterRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/dashboard/audit': typeof AdminAdminDashboardAuditRoute
  '/admin/dashboard/blog': typeof AdminAdminDashboardBlogRouteWithChildren
  '/admin/dashboard/clients': typeof AdminAdminDashboardClientsRouteWithChildren
  '/admin/dashboard/partners': typeof AdminAdminDashboardPartnersRoute
  '/admin/dashboard/portfolio': typeof AdminAdminDashboardPortfolioRouteWithChildren
  '/admin/dashboard/services': typeof AdminAdminDashboardServicesRoute
  '/admin/dashboard/settings': typeof AdminAdminDashboardSettingsRoute
  '/admin/dashboard/submissions': typeof AdminAdminDashboardSubmissionsRoute
  '/admin/dashboard/': typeof AdminAdminDashboardIndexRoute
  '/admin/dashboard/blog/$id': typeof AdminAdminDashboardBlogIdRoute
  '/admin/dashboard/clients/$id': typeof AdminAdminDashboardClientsIdRoute
  '/admin/dashboard/portfolio/$id': typeof AdminAdminDashboardPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/integration': typeof PartnerIntegrationRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/chat': typeof ProductsChatRoute
  '/products/flow': typeof ProductsFlowRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/custom-agentic-ai': typeof ServicesCustomAgenticAiRoute
  '/services/custom-ai-systems': typeof ServicesCustomAiSystemsRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/utilities/background-remover': typeof UtilitiesBackgroundRemoverRoute
  '/utilities/csv-cleaner': typeof UtilitiesCsvCleanerRoute
  '/utilities/email-signature-generator': typeof UtilitiesEmailSignatureGeneratorRoute
  '/utilities/file-compressor': typeof UtilitiesFileCompressorRoute
  '/utilities/file-converter': typeof UtilitiesFileConverterRoute
  '/utilities/image-compressor': typeof UtilitiesImageCompressorRoute
  '/utilities/image-converter': typeof UtilitiesImageConverterRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/utilities': typeof UtilitiesIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/dashboard/audit': typeof AdminAdminDashboardAuditRoute
  '/admin/dashboard/blog': typeof AdminAdminDashboardBlogRouteWithChildren
  '/admin/dashboard/clients': typeof AdminAdminDashboardClientsRouteWithChildren
  '/admin/dashboard/partners': typeof AdminAdminDashboardPartnersRoute
  '/admin/dashboard/portfolio': typeof AdminAdminDashboardPortfolioRouteWithChildren
  '/admin/dashboard/services': typeof AdminAdminDashboardServicesRoute
  '/admin/dashboard/settings': typeof AdminAdminDashboardSettingsRoute
  '/admin/dashboard/submissions': typeof AdminAdminDashboardSubmissionsRoute
  '/admin/dashboard': typeof AdminAdminDashboardIndexRoute
  '/admin/dashboard/blog/$id': typeof AdminAdminDashboardBlogIdRoute
  '/admin/dashboard/clients/$id': typeof AdminAdminDashboardClientsIdRoute
  '/admin/dashboard/portfolio/$id': typeof AdminAdminDashboardPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/talk-to-us': typeof TalkToUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/integration': typeof PartnerIntegrationRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/chat': typeof ProductsChatRoute
  '/products/flow': typeof ProductsFlowRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/custom-agentic-ai': typeof ServicesCustomAgenticAiRoute
  '/services/custom-ai-systems': typeof ServicesCustomAiSystemsRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/utilities/background-remover': typeof UtilitiesBackgroundRemoverRoute
  '/utilities/csv-cleaner': typeof UtilitiesCsvCleanerRoute
  '/utilities/email-signature-generator': typeof UtilitiesEmailSignatureGeneratorRoute
  '/utilities/file-compressor': typeof UtilitiesFileCompressorRoute
  '/utilities/file-converter': typeof UtilitiesFileConverterRoute
  '/utilities/image-compressor': typeof UtilitiesImageCompressorRoute
  '/utilities/image-converter': typeof UtilitiesImageConverterRoute
  '/utilities/qr-code-generator': typeof UtilitiesQrCodeGeneratorRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/_admin/admin/dashboard/audit': typeof AdminAdminDashboardAuditRoute
  '/_admin/admin/dashboard/blog': typeof AdminAdminDashboardBlogRouteWithChildren
  '/_admin/admin/dashboard/clients': typeof AdminAdminDashboardClientsRouteWithChildren
  '/_admin/admin/dashboard/partners': typeof AdminAdminDashboardPartnersRoute
  '/_admin/admin/dashboard/portfolio': typeof AdminAdminDashboardPortfolioRouteWithChildren
  '/_admin/admin/dashboard/services': typeof AdminAdminDashboardServicesRoute
  '/_admin/admin/dashboard/settings': typeof AdminAdminDashboardSettingsRoute
  '/_admin/admin/dashboard/submissions': typeof AdminAdminDashboardSubmissionsRoute
  '/_admin/admin/dashboard/': typeof AdminAdminDashboardIndexRoute
  '/_admin/admin/dashboard/blog/$id': typeof AdminAdminDashboardBlogIdRoute
  '/_admin/admin/dashboard/clients/$id': typeof AdminAdminDashboardClientsIdRoute
  '/_admin/admin/dashboard/portfolio/$id': typeof AdminAdminDashboardPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/talk-to-us'
    | '/admin/login'
    | '/admin/mfa'
    | '/api/submit-form'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/integration'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/products/chat'
    | '/products/flow'
    | '/services/ai-voice-agent'
    | '/services/custom-agentic-ai'
    | '/services/custom-ai-systems'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/utilities/background-remover'
    | '/utilities/csv-cleaner'
    | '/utilities/email-signature-generator'
    | '/utilities/file-compressor'
    | '/utilities/file-converter'
    | '/utilities/image-compressor'
    | '/utilities/image-converter'
    | '/utilities/qr-code-generator'
    | '/blog/'
    | '/industries/'
    | '/partner/'
    | '/products/'
    | '/services/'
    | '/utilities/'
    | '/admin/dashboard'
    | '/api/admin/upload'
    | '/admin/dashboard/audit'
    | '/admin/dashboard/blog'
    | '/admin/dashboard/clients'
    | '/admin/dashboard/partners'
    | '/admin/dashboard/portfolio'
    | '/admin/dashboard/services'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/submissions'
    | '/admin/dashboard/'
    | '/admin/dashboard/blog/$id'
    | '/admin/dashboard/clients/$id'
    | '/admin/dashboard/portfolio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/talk-to-us'
    | '/admin/login'
    | '/admin/mfa'
    | '/api/submit-form'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/integration'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/products/chat'
    | '/products/flow'
    | '/services/ai-voice-agent'
    | '/services/custom-agentic-ai'
    | '/services/custom-ai-systems'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/utilities/background-remover'
    | '/utilities/csv-cleaner'
    | '/utilities/email-signature-generator'
    | '/utilities/file-compressor'
    | '/utilities/file-converter'
    | '/utilities/image-compressor'
    | '/utilities/image-converter'
    | '/utilities/qr-code-generator'
    | '/blog'
    | '/industries'
    | '/partner'
    | '/products'
    | '/services'
    | '/utilities'
    | '/api/admin/upload'
    | '/admin/dashboard/audit'
    | '/admin/dashboard/blog'
    | '/admin/dashboard/clients'
    | '/admin/dashboard/partners'
    | '/admin/dashboard/portfolio'
    | '/admin/dashboard/services'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/submissions'
    | '/admin/dashboard'
    | '/admin/dashboard/blog/$id'
    | '/admin/dashboard/clients/$id'
    | '/admin/dashboard/portfolio/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/talk-to-us'
    | '/admin/login'
    | '/admin/mfa'
    | '/api/submit-form'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/integration'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/products/chat'
    | '/products/flow'
    | '/services/ai-voice-agent'
    | '/services/custom-agentic-ai'
    | '/services/custom-ai-systems'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/utilities/background-remover'
    | '/utilities/csv-cleaner'
    | '/utilities/email-signature-generator'
    | '/utilities/file-compressor'
    | '/utilities/file-converter'
    | '/utilities/image-compressor'
    | '/utilities/image-converter'
    | '/utilities/qr-code-generator'
    | '/blog/'
    | '/industries/'
    | '/partner/'
    | '/products/'
    | '/services/'
    | '/utilities/'
    | '/_admin/admin/dashboard'
    | '/api/admin/upload'
    | '/_admin/admin/dashboard/audit'
    | '/_admin/admin/dashboard/blog'
    | '/_admin/admin/dashboard/clients'
    | '/_admin/admin/dashboard/partners'
    | '/_admin/admin/dashboard/portfolio'
    | '/_admin/admin/dashboard/services'
    | '/_admin/admin/dashboard/settings'
    | '/_admin/admin/dashboard/submissions'
    | '/_admin/admin/dashboard/'
    | '/_admin/admin/dashboard/blog/$id'
    | '/_admin/admin/dashboard/clients/$id'
    | '/_admin/admin/dashboard/portfolio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  HelpRoute: typeof HelpRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  TalkToUsRoute: typeof TalkToUsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMfaRoute: typeof AdminMfaRoute
  ApiSubmitFormRoute: typeof ApiSubmitFormRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalRefundPolicyRoute: typeof LegalRefundPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  PartnerAgencyRoute: typeof PartnerAgencyRoute
  PartnerIntegrationRoute: typeof PartnerIntegrationRoute
  PartnerReferralRoute: typeof PartnerReferralRoute
  ProductsChatRoute: typeof ProductsChatRoute
  ProductsFlowRoute: typeof ProductsFlowRoute
  ServicesAiVoiceAgentRoute: typeof ServicesAiVoiceAgentRoute
  ServicesCustomAgenticAiRoute: typeof ServicesCustomAgenticAiRoute
  ServicesCustomAiSystemsRoute: typeof ServicesCustomAiSystemsRoute
  ServicesLeadReactivationRoute: typeof ServicesLeadReactivationRoute
  ServicesSpeedToLeadRoute: typeof ServicesSpeedToLeadRoute
  UtilitiesBackgroundRemoverRoute: typeof UtilitiesBackgroundRemoverRoute
  UtilitiesCsvCleanerRoute: typeof UtilitiesCsvCleanerRoute
  UtilitiesEmailSignatureGeneratorRoute: typeof UtilitiesEmailSignatureGeneratorRoute
  UtilitiesFileCompressorRoute: typeof UtilitiesFileCompressorRoute
  UtilitiesFileConverterRoute: typeof UtilitiesFileConverterRoute
  UtilitiesImageCompressorRoute: typeof UtilitiesImageCompressorRoute
  UtilitiesImageConverterRoute: typeof UtilitiesImageConverterRoute
  UtilitiesQrCodeGeneratorRoute: typeof UtilitiesQrCodeGeneratorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  UtilitiesIndexRoute: typeof UtilitiesIndexRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk-to-us': {
      id: '/talk-to-us'
      path: '/talk-to-us'
      fullPath: '/talk-to-us'
      preLoaderRoute: typeof TalkToUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/': {
      id: '/utilities/'
      path: '/utilities'
      fullPath: '/utilities/'
      preLoaderRoute: typeof UtilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/qr-code-generator': {
      id: '/utilities/qr-code-generator'
      path: '/utilities/qr-code-generator'
      fullPath: '/utilities/qr-code-generator'
      preLoaderRoute: typeof UtilitiesQrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/image-converter': {
      id: '/utilities/image-converter'
      path: '/utilities/image-converter'
      fullPath: '/utilities/image-converter'
      preLoaderRoute: typeof UtilitiesImageConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/image-compressor': {
      id: '/utilities/image-compressor'
      path: '/utilities/image-compressor'
      fullPath: '/utilities/image-compressor'
      preLoaderRoute: typeof UtilitiesImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/file-converter': {
      id: '/utilities/file-converter'
      path: '/utilities/file-converter'
      fullPath: '/utilities/file-converter'
      preLoaderRoute: typeof UtilitiesFileConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/file-compressor': {
      id: '/utilities/file-compressor'
      path: '/utilities/file-compressor'
      fullPath: '/utilities/file-compressor'
      preLoaderRoute: typeof UtilitiesFileCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/email-signature-generator': {
      id: '/utilities/email-signature-generator'
      path: '/utilities/email-signature-generator'
      fullPath: '/utilities/email-signature-generator'
      preLoaderRoute: typeof UtilitiesEmailSignatureGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/csv-cleaner': {
      id: '/utilities/csv-cleaner'
      path: '/utilities/csv-cleaner'
      fullPath: '/utilities/csv-cleaner'
      preLoaderRoute: typeof UtilitiesCsvCleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/background-remover': {
      id: '/utilities/background-remover'
      path: '/utilities/background-remover'
      fullPath: '/utilities/background-remover'
      preLoaderRoute: typeof UtilitiesBackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/speed-to-lead': {
      id: '/services/speed-to-lead'
      path: '/services/speed-to-lead'
      fullPath: '/services/speed-to-lead'
      preLoaderRoute: typeof ServicesSpeedToLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lead-reactivation': {
      id: '/services/lead-reactivation'
      path: '/services/lead-reactivation'
      fullPath: '/services/lead-reactivation'
      preLoaderRoute: typeof ServicesLeadReactivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-ai-systems': {
      id: '/services/custom-ai-systems'
      path: '/services/custom-ai-systems'
      fullPath: '/services/custom-ai-systems'
      preLoaderRoute: typeof ServicesCustomAiSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-agentic-ai': {
      id: '/services/custom-agentic-ai'
      path: '/services/custom-agentic-ai'
      fullPath: '/services/custom-agentic-ai'
      preLoaderRoute: typeof ServicesCustomAgenticAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-voice-agent': {
      id: '/services/ai-voice-agent'
      path: '/services/ai-voice-agent'
      fullPath: '/services/ai-voice-agent'
      preLoaderRoute: typeof ServicesAiVoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/flow': {
      id: '/products/flow'
      path: '/products/flow'
      fullPath: '/products/flow'
      preLoaderRoute: typeof ProductsFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/chat': {
      id: '/products/chat'
      path: '/products/chat'
      fullPath: '/products/chat'
      preLoaderRoute: typeof ProductsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/partner/referral': {
      id: '/partner/referral'
      path: '/partner/referral'
      fullPath: '/partner/referral'
      preLoaderRoute: typeof PartnerReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/integration': {
      id: '/partner/integration'
      path: '/partner/integration'
      fullPath: '/partner/integration'
      preLoaderRoute: typeof PartnerIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/agency': {
      id: '/partner/agency'
      path: '/partner/agency'
      fullPath: '/partner/agency'
      preLoaderRoute: typeof PartnerAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund-policy': {
      id: '/legal/refund-policy'
      path: '/legal/refund-policy'
      fullPath: '/legal/refund-policy'
      preLoaderRoute: typeof LegalRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-form': {
      id: '/api/submit-form'
      path: '/api/submit-form'
      fullPath: '/api/submit-form'
      preLoaderRoute: typeof ApiSubmitFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/admin/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard/': {
      id: '/_admin/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminAdminDashboardIndexRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/submissions': {
      id: '/_admin/admin/dashboard/submissions'
      path: '/submissions'
      fullPath: '/admin/dashboard/submissions'
      preLoaderRoute: typeof AdminAdminDashboardSubmissionsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/settings': {
      id: '/_admin/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminAdminDashboardSettingsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/services': {
      id: '/_admin/admin/dashboard/services'
      path: '/services'
      fullPath: '/admin/dashboard/services'
      preLoaderRoute: typeof AdminAdminDashboardServicesRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/portfolio': {
      id: '/_admin/admin/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/admin/dashboard/portfolio'
      preLoaderRoute: typeof AdminAdminDashboardPortfolioRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/partners': {
      id: '/_admin/admin/dashboard/partners'
      path: '/partners'
      fullPath: '/admin/dashboard/partners'
      preLoaderRoute: typeof AdminAdminDashboardPartnersRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/clients': {
      id: '/_admin/admin/dashboard/clients'
      path: '/clients'
      fullPath: '/admin/dashboard/clients'
      preLoaderRoute: typeof AdminAdminDashboardClientsRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/blog': {
      id: '/_admin/admin/dashboard/blog'
      path: '/blog'
      fullPath: '/admin/dashboard/blog'
      preLoaderRoute: typeof AdminAdminDashboardBlogRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/audit': {
      id: '/_admin/admin/dashboard/audit'
      path: '/audit'
      fullPath: '/admin/dashboard/audit'
      preLoaderRoute: typeof AdminAdminDashboardAuditRouteImport
      parentRoute: typeof AdminAdminDashboardRoute
    }
    '/_admin/admin/dashboard/portfolio/$id': {
      id: '/_admin/admin/dashboard/portfolio/$id'
      path: '/$id'
      fullPath: '/admin/dashboard/portfolio/$id'
      preLoaderRoute: typeof AdminAdminDashboardPortfolioIdRouteImport
      parentRoute: typeof AdminAdminDashboardPortfolioRoute
    }
    '/_admin/admin/dashboard/clients/$id': {
      id: '/_admin/admin/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/admin/dashboard/clients/$id'
      preLoaderRoute: typeof AdminAdminDashboardClientsIdRouteImport
      parentRoute: typeof AdminAdminDashboardClientsRoute
    }
    '/_admin/admin/dashboard/blog/$id': {
      id: '/_admin/admin/dashboard/blog/$id'
      path: '/$id'
      fullPath: '/admin/dashboard/blog/$id'
      preLoaderRoute: typeof AdminAdminDashboardBlogIdRouteImport
      parentRoute: typeof AdminAdminDashboardBlogRoute
    }
  }
}

interface AdminAdminDashboardBlogRouteChildren {
  AdminAdminDashboardBlogIdRoute: typeof AdminAdminDashboardBlogIdRoute
}

const AdminAdminDashboardBlogRouteChildren: AdminAdminDashboardBlogRouteChildren =
  {
    AdminAdminDashboardBlogIdRoute: AdminAdminDashboardBlogIdRoute,
  }

const AdminAdminDashboardBlogRouteWithChildren =
  AdminAdminDashboardBlogRoute._addFileChildren(
    AdminAdminDashboardBlogRouteChildren,
  )

interface AdminAdminDashboardClientsRouteChildren {
  AdminAdminDashboardClientsIdRoute: typeof AdminAdminDashboardClientsIdRoute
}

const AdminAdminDashboardClientsRouteChildren: AdminAdminDashboardClientsRouteChildren =
  {
    AdminAdminDashboardClientsIdRoute: AdminAdminDashboardClientsIdRoute,
  }

const AdminAdminDashboardClientsRouteWithChildren =
  AdminAdminDashboardClientsRoute._addFileChildren(
    AdminAdminDashboardClientsRouteChildren,
  )

interface AdminAdminDashboardPortfolioRouteChildren {
  AdminAdminDashboardPortfolioIdRoute: typeof AdminAdminDashboardPortfolioIdRoute
}

const AdminAdminDashboardPortfolioRouteChildren: AdminAdminDashboardPortfolioRouteChildren =
  {
    AdminAdminDashboardPortfolioIdRoute: AdminAdminDashboardPortfolioIdRoute,
  }

const AdminAdminDashboardPortfolioRouteWithChildren =
  AdminAdminDashboardPortfolioRoute._addFileChildren(
    AdminAdminDashboardPortfolioRouteChildren,
  )

interface AdminAdminDashboardRouteChildren {
  AdminAdminDashboardAuditRoute: typeof AdminAdminDashboardAuditRoute
  AdminAdminDashboardBlogRoute: typeof AdminAdminDashboardBlogRouteWithChildren
  AdminAdminDashboardClientsRoute: typeof AdminAdminDashboardClientsRouteWithChildren
  AdminAdminDashboardPartnersRoute: typeof AdminAdminDashboardPartnersRoute
  AdminAdminDashboardPortfolioRoute: typeof AdminAdminDashboardPortfolioRouteWithChildren
  AdminAdminDashboardServicesRoute: typeof AdminAdminDashboardServicesRoute
  AdminAdminDashboardSettingsRoute: typeof AdminAdminDashboardSettingsRoute
  AdminAdminDashboardSubmissionsRoute: typeof AdminAdminDashboardSubmissionsRoute
  AdminAdminDashboardIndexRoute: typeof AdminAdminDashboardIndexRoute
}

const AdminAdminDashboardRouteChildren: AdminAdminDashboardRouteChildren = {
  AdminAdminDashboardAuditRoute: AdminAdminDashboardAuditRoute,
  AdminAdminDashboardBlogRoute: AdminAdminDashboardBlogRouteWithChildren,
  AdminAdminDashboardClientsRoute: AdminAdminDashboardClientsRouteWithChildren,
  AdminAdminDashboardPartnersRoute: AdminAdminDashboardPartnersRoute,
  AdminAdminDashboardPortfolioRoute:
    AdminAdminDashboardPortfolioRouteWithChildren,
  AdminAdminDashboardServicesRoute: AdminAdminDashboardServicesRoute,
  AdminAdminDashboardSettingsRoute: AdminAdminDashboardSettingsRoute,
  AdminAdminDashboardSubmissionsRoute: AdminAdminDashboardSubmissionsRoute,
  AdminAdminDashboardIndexRoute: AdminAdminDashboardIndexRoute,
}

const AdminAdminDashboardRouteWithChildren =
  AdminAdminDashboardRoute._addFileChildren(AdminAdminDashboardRouteChildren)

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  HelpRoute: HelpRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  TalkToUsRoute: TalkToUsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMfaRoute: AdminMfaRoute,
  ApiSubmitFormRoute: ApiSubmitFormRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalRefundPolicyRoute: LegalRefundPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  PartnerAgencyRoute: PartnerAgencyRoute,
  PartnerIntegrationRoute: PartnerIntegrationRoute,
  PartnerReferralRoute: PartnerReferralRoute,
  ProductsChatRoute: ProductsChatRoute,
  ProductsFlowRoute: ProductsFlowRoute,
  ServicesAiVoiceAgentRoute: ServicesAiVoiceAgentRoute,
  ServicesCustomAgenticAiRoute: ServicesCustomAgenticAiRoute,
  ServicesCustomAiSystemsRoute: ServicesCustomAiSystemsRoute,
  ServicesLeadReactivationRoute: ServicesLeadReactivationRoute,
  ServicesSpeedToLeadRoute: ServicesSpeedToLeadRoute,
  UtilitiesBackgroundRemoverRoute: UtilitiesBackgroundRemoverRoute,
  UtilitiesCsvCleanerRoute: UtilitiesCsvCleanerRoute,
  UtilitiesEmailSignatureGeneratorRoute: UtilitiesEmailSignatureGeneratorRoute,
  UtilitiesFileCompressorRoute: UtilitiesFileCompressorRoute,
  UtilitiesFileConverterRoute: UtilitiesFileConverterRoute,
  UtilitiesImageCompressorRoute: UtilitiesImageCompressorRoute,
  UtilitiesImageConverterRoute: UtilitiesImageConverterRoute,
  UtilitiesQrCodeGeneratorRoute: UtilitiesQrCodeGeneratorRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  UtilitiesIndexRoute: UtilitiesIndexRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
