/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as ServicesVirtualPhotoshootRouteImport } from './routes/services.virtual-photoshoot'
import { Route as ServicesSpeedToLeadRouteImport } from './routes/services.speed-to-lead'
import { Route as ServicesLeadReactivationRouteImport } from './routes/services.lead-reactivation'
import { Route as ServicesAutomatedHiringRouteImport } from './routes/services.automated-hiring'
import { Route as ServicesAiWhatsappAgentRouteImport } from './routes/services.ai-whatsapp-agent'
import { Route as ServicesAiWebWidgetRouteImport } from './routes/services.ai-web-widget'
import { Route as ServicesAiVoiceAgentRouteImport } from './routes/services.ai-voice-agent'
import { Route as ServicesAiKnowledgeBaseRouteImport } from './routes/services.ai-knowledge-base'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as PartnerReferralRouteImport } from './routes/partner.referral'
import { Route as PartnerAgencyRouteImport } from './routes/partner.agency'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'
import { Route as LegalRefundPolicyRouteImport } from './routes/legal.refund-policy'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as ApiSubmitFormRouteImport } from './routes/api/submit-form'

const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVirtualPhotoshootRoute =
  ServicesVirtualPhotoshootRouteImport.update({
    id: '/services/virtual-photoshoot',
    path: '/services/virtual-photoshoot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSpeedToLeadRoute = ServicesSpeedToLeadRouteImport.update({
  id: '/services/speed-to-lead',
  path: '/services/speed-to-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeadReactivationRoute =
  ServicesLeadReactivationRouteImport.update({
    id: '/services/lead-reactivation',
    path: '/services/lead-reactivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAutomatedHiringRoute = ServicesAutomatedHiringRouteImport.update({
  id: '/services/automated-hiring',
  path: '/services/automated-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiWhatsappAgentRoute = ServicesAiWhatsappAgentRouteImport.update({
  id: '/services/ai-whatsapp-agent',
  path: '/services/ai-whatsapp-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiWebWidgetRoute = ServicesAiWebWidgetRouteImport.update({
  id: '/services/ai-web-widget',
  path: '/services/ai-web-widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiVoiceAgentRoute = ServicesAiVoiceAgentRouteImport.update({
  id: '/services/ai-voice-agent',
  path: '/services/ai-voice-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiKnowledgeBaseRoute = ServicesAiKnowledgeBaseRouteImport.update({
  id: '/services/ai-knowledge-base',
  path: '/services/ai-knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const PartnerReferralRoute = PartnerReferralRouteImport.update({
  id: '/partner/referral',
  path: '/partner/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAgencyRoute = PartnerAgencyRouteImport.update({
  id: '/partner/agency',
  path: '/partner/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundPolicyRoute = LegalRefundPolicyRouteImport.update({
  id: '/legal/refund-policy',
  path: '/legal/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitFormRoute = ApiSubmitFormRouteImport.update({
  id: '/api/submit-form',
  path: '/api/submit-form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/ai-knowledge-base': typeof ServicesAiKnowledgeBaseRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/ai-web-widget': typeof ServicesAiWebWidgetRoute
  '/services/ai-whatsapp-agent': typeof ServicesAiWhatsappAgentRoute
  '/services/automated-hiring': typeof ServicesAutomatedHiringRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/services/virtual-photoshoot': typeof ServicesVirtualPhotoshootRoute
  '/partner/': typeof PartnerIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/ai-knowledge-base': typeof ServicesAiKnowledgeBaseRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/ai-web-widget': typeof ServicesAiWebWidgetRoute
  '/services/ai-whatsapp-agent': typeof ServicesAiWhatsappAgentRoute
  '/services/automated-hiring': typeof ServicesAutomatedHiringRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/services/virtual-photoshoot': typeof ServicesVirtualPhotoshootRoute
  '/partner': typeof PartnerIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/api/submit-form': typeof ApiSubmitFormRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/refund-policy': typeof LegalRefundPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/partner/agency': typeof PartnerAgencyRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/ai-knowledge-base': typeof ServicesAiKnowledgeBaseRoute
  '/services/ai-voice-agent': typeof ServicesAiVoiceAgentRoute
  '/services/ai-web-widget': typeof ServicesAiWebWidgetRoute
  '/services/ai-whatsapp-agent': typeof ServicesAiWhatsappAgentRoute
  '/services/automated-hiring': typeof ServicesAutomatedHiringRoute
  '/services/lead-reactivation': typeof ServicesLeadReactivationRoute
  '/services/speed-to-lead': typeof ServicesSpeedToLeadRoute
  '/services/virtual-photoshoot': typeof ServicesVirtualPhotoshootRoute
  '/partner/': typeof PartnerIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/api/submit-form'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/services/ai-knowledge-base'
    | '/services/ai-voice-agent'
    | '/services/ai-web-widget'
    | '/services/ai-whatsapp-agent'
    | '/services/automated-hiring'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/services/virtual-photoshoot'
    | '/partner/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/api/submit-form'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/services/ai-knowledge-base'
    | '/services/ai-voice-agent'
    | '/services/ai-web-widget'
    | '/services/ai-whatsapp-agent'
    | '/services/automated-hiring'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/services/virtual-photoshoot'
    | '/partner'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/portfolio'
    | '/pricing'
    | '/roi-calculator'
    | '/api/submit-form'
    | '/legal/privacy-policy'
    | '/legal/refund-policy'
    | '/legal/terms-of-service'
    | '/partner/agency'
    | '/partner/referral'
    | '/portfolio/$slug'
    | '/services/ai-knowledge-base'
    | '/services/ai-voice-agent'
    | '/services/ai-web-widget'
    | '/services/ai-whatsapp-agent'
    | '/services/automated-hiring'
    | '/services/lead-reactivation'
    | '/services/speed-to-lead'
    | '/services/virtual-photoshoot'
    | '/partner/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  ApiSubmitFormRoute: typeof ApiSubmitFormRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalRefundPolicyRoute: typeof LegalRefundPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  PartnerAgencyRoute: typeof PartnerAgencyRoute
  PartnerReferralRoute: typeof PartnerReferralRoute
  ServicesAiKnowledgeBaseRoute: typeof ServicesAiKnowledgeBaseRoute
  ServicesAiVoiceAgentRoute: typeof ServicesAiVoiceAgentRoute
  ServicesAiWebWidgetRoute: typeof ServicesAiWebWidgetRoute
  ServicesAiWhatsappAgentRoute: typeof ServicesAiWhatsappAgentRoute
  ServicesAutomatedHiringRoute: typeof ServicesAutomatedHiringRoute
  ServicesLeadReactivationRoute: typeof ServicesLeadReactivationRoute
  ServicesSpeedToLeadRoute: typeof ServicesSpeedToLeadRoute
  ServicesVirtualPhotoshootRoute: typeof ServicesVirtualPhotoshootRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/virtual-photoshoot': {
      id: '/services/virtual-photoshoot'
      path: '/services/virtual-photoshoot'
      fullPath: '/services/virtual-photoshoot'
      preLoaderRoute: typeof ServicesVirtualPhotoshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/speed-to-lead': {
      id: '/services/speed-to-lead'
      path: '/services/speed-to-lead'
      fullPath: '/services/speed-to-lead'
      preLoaderRoute: typeof ServicesSpeedToLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lead-reactivation': {
      id: '/services/lead-reactivation'
      path: '/services/lead-reactivation'
      fullPath: '/services/lead-reactivation'
      preLoaderRoute: typeof ServicesLeadReactivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automated-hiring': {
      id: '/services/automated-hiring'
      path: '/services/automated-hiring'
      fullPath: '/services/automated-hiring'
      preLoaderRoute: typeof ServicesAutomatedHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-whatsapp-agent': {
      id: '/services/ai-whatsapp-agent'
      path: '/services/ai-whatsapp-agent'
      fullPath: '/services/ai-whatsapp-agent'
      preLoaderRoute: typeof ServicesAiWhatsappAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-web-widget': {
      id: '/services/ai-web-widget'
      path: '/services/ai-web-widget'
      fullPath: '/services/ai-web-widget'
      preLoaderRoute: typeof ServicesAiWebWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-voice-agent': {
      id: '/services/ai-voice-agent'
      path: '/services/ai-voice-agent'
      fullPath: '/services/ai-voice-agent'
      preLoaderRoute: typeof ServicesAiVoiceAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-knowledge-base': {
      id: '/services/ai-knowledge-base'
      path: '/services/ai-knowledge-base'
      fullPath: '/services/ai-knowledge-base'
      preLoaderRoute: typeof ServicesAiKnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/partner/referral': {
      id: '/partner/referral'
      path: '/partner/referral'
      fullPath: '/partner/referral'
      preLoaderRoute: typeof PartnerReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/agency': {
      id: '/partner/agency'
      path: '/partner/agency'
      fullPath: '/partner/agency'
      preLoaderRoute: typeof PartnerAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund-policy': {
      id: '/legal/refund-policy'
      path: '/legal/refund-policy'
      fullPath: '/legal/refund-policy'
      preLoaderRoute: typeof LegalRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-form': {
      id: '/api/submit-form'
      path: '/api/submit-form'
      fullPath: '/api/submit-form'
      preLoaderRoute: typeof ApiSubmitFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  ApiSubmitFormRoute: ApiSubmitFormRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalRefundPolicyRoute: LegalRefundPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  PartnerAgencyRoute: PartnerAgencyRoute,
  PartnerReferralRoute: PartnerReferralRoute,
  ServicesAiKnowledgeBaseRoute: ServicesAiKnowledgeBaseRoute,
  ServicesAiVoiceAgentRoute: ServicesAiVoiceAgentRoute,
  ServicesAiWebWidgetRoute: ServicesAiWebWidgetRoute,
  ServicesAiWhatsappAgentRoute: ServicesAiWhatsappAgentRoute,
  ServicesAutomatedHiringRoute: ServicesAutomatedHiringRoute,
  ServicesLeadReactivationRoute: ServicesLeadReactivationRoute,
  ServicesSpeedToLeadRoute: ServicesSpeedToLeadRoute,
  ServicesVirtualPhotoshootRoute: ServicesVirtualPhotoshootRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
