// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewawqqthsmrcklxfcmkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YXdxcXRoc21yY2tseGZjbWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3NDY4NzQsImV4cCI6MjA5ODMyMjg3NH0.Wh41bGGKBkuaskNof6vERu2twanhnXLcOteFlavDhgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});